name: sync-fork

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch: {}

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - run: gh repo sync $REPOSITORY -b $BRANCH_NAME
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPOSITORY: ${{ github.repository }}
          BRANCH_NAME: ${{ github.ref_name }}

      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}

      - uses: actions/setup-node@v4
        with:
          node-version: ">=20"

      - run: yarn

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "[Auto] Push yarn.lock"
